name: "One step up"
on: [push]

jobs:
  seasonal_greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Merry Xmas!
        env:
          greeting: "Merry"
          season: "Xmas"
        run: export SENTENCE="$greeting $season!"
      - name: Greet
        id: greet
        run: python -c "import os; print(os.environ.keys)"
      - name: Run Ruby
        env:
          OUTPUT: ${{ steps.greet.outputs }}
        run: /opt/hostedtoolcache/Ruby/2.6.3/x64/bin/ruby -e "puts ENV['OUTPUT']"
