name: "One step up"
on: [push]

jobs:
  seasonal_greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Merry Xmas!
        id: pre
        env:
          greeting: "Merry"
          season: "Xmas"
        run: export $SENTENCE="$greeting $season!"
      - name: Greet
        run: python -c "import os; print(os.environ['SENTENCE'])"
