name: "One step up"
on: [push]

jobs:
  seasonal_greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Merry Xmas!
        env:
          greeting: "Merry"
          season: "Xmas"
        run: SENTENCE="$greeting $season!"
      - name: Greet
        id: greet
        run: python -c "import os; print(os.environ.keys)"
      - name: Got
        with:
          ruby-version: '2.x'
        env:
          OUTPUT: ${{ steps.greet.outputs }}
        run: ruby -e "puts ENV['OUTPUT']"
